name: flutter_beacon_riverpod
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_beacon: ^0.5.1
  flutter_hooks: ^0.18.2+1
  freezed_annotation: null
  hooks_riverpod: ^1.0.3
  json_serializable: null

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: null
  
flutter:
  uses-material-design: true
